version: '3.8'

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - REACT_APP_API_URL=http://development.greenenco.in
    restart: always
    networks:
      - app-network

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
