version: '3.8'

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
        - 3000:3000
    depends_on:
       backend:
          condition: service_healthy
    restart: always
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3000"]
      timeout: 10s
      retries: 5
    networks:
      - app-network

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
        - 5000:5000
    restart: always
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:5000"]
      timeout: 10s
      retries: 5
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
